/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { Person } from './person';
import { Location } from './location';


export interface Address { 
    id?: number;
    name: string;
    orderNumber: number;
    location: Location;
    person?: Person;
    department?: Department;
}

