/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Announcement { 
    id?: number;
    xmin?: number;
    announcementType: Announcement.AnnouncementTypeEnum;
    title: string;
    body: string;
    releaseDate: string;
    expireDate: string;
}
export namespace Announcement {
    export type AnnouncementTypeEnum = 'Public' | 'Private';
    export const AnnouncementTypeEnum = {
        Public: 'Public' as AnnouncementTypeEnum,
        Private: 'Private' as AnnouncementTypeEnum
    };
}


