/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BeaconResponse { 
    status?: boolean;
    activityType?: BeaconResponse.ActivityTypeEnum;
    activityDate?: string;
}
export namespace BeaconResponse {
    export type ActivityTypeEnum = 'CHECKIN' | 'CHECKOUT' | 'BREAKIN' | 'BREAKOUT';
    export const ActivityTypeEnum = {
        Checkin: 'CHECKIN' as ActivityTypeEnum,
        Checkout: 'CHECKOUT' as ActivityTypeEnum,
        Breakin: 'BREAKIN' as ActivityTypeEnum,
        Breakout: 'BREAKOUT' as ActivityTypeEnum
    };
}


