/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CommonUnits { 
    id?: number;
    xmin?: number;
    measure: CommonUnits.MeasureEnum;
    abbr: string;
    system: CommonUnits.SystemEnum;
    singular: string;
    plural?: string;
}
export namespace CommonUnits {
    export type MeasureEnum = 'Temperature' | 'Percent' | 'Time' | 'Frequency' | 'Length' | 'Area' | 'Mass' | 'VolumeFlowRate' | 'Speed' | 'Pace' | 'Pressure' | 'Digital' | 'Illuminance' | 'PartsPer' | 'Voltage' | 'Current' | 'Power' | 'ApparentPower' | 'ReactivePower' | 'Energy' | 'ReactiveEnergy' | 'Angle' | 'Count';
    export const MeasureEnum = {
        Temperature: 'Temperature' as MeasureEnum,
        Percent: 'Percent' as MeasureEnum,
        Time: 'Time' as MeasureEnum,
        Frequency: 'Frequency' as MeasureEnum,
        Length: 'Length' as MeasureEnum,
        Area: 'Area' as MeasureEnum,
        Mass: 'Mass' as MeasureEnum,
        VolumeFlowRate: 'VolumeFlowRate' as MeasureEnum,
        Speed: 'Speed' as MeasureEnum,
        Pace: 'Pace' as MeasureEnum,
        Pressure: 'Pressure' as MeasureEnum,
        Digital: 'Digital' as MeasureEnum,
        Illuminance: 'Illuminance' as MeasureEnum,
        PartsPer: 'PartsPer' as MeasureEnum,
        Voltage: 'Voltage' as MeasureEnum,
        Current: 'Current' as MeasureEnum,
        Power: 'Power' as MeasureEnum,
        ApparentPower: 'ApparentPower' as MeasureEnum,
        ReactivePower: 'ReactivePower' as MeasureEnum,
        Energy: 'Energy' as MeasureEnum,
        ReactiveEnergy: 'ReactiveEnergy' as MeasureEnum,
        Angle: 'Angle' as MeasureEnum,
        Count: 'Count' as MeasureEnum
    };
    export type SystemEnum = 'metric';
    export const SystemEnum = {
        Metric: 'metric' as SystemEnum
    };
}


