/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { Person } from './person';


export interface Contact { 
    id?: number;
    xmin?: number;
    contactType: Contact.ContactTypeEnum;
    label: string;
    person?: Person;
    department?: Department;
    sendNotification?: boolean;
}
export namespace Contact {
    export type ContactTypeEnum = 'Address' | 'Email' | 'Phone' | 'Fax' | 'Intercom';
    export const ContactTypeEnum = {
        Address: 'Address' as ContactTypeEnum,
        Email: 'Email' as ContactTypeEnum,
        Phone: 'Phone' as ContactTypeEnum,
        Fax: 'Fax' as ContactTypeEnum,
        Intercom: 'Intercom' as ContactTypeEnum
    };
}


