/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface Dashboard { 
    id?: number;
    xmin?: number;
    orderNumber?: number;
    title: string;
    description: string;
    dashboardId: number;
    roles?: Set<Role>;
}

