/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Document { 
    id?: number;
    xmin?: number;
    title: string;
    description: string;
    documentType?: Document.DocumentTypeEnum;
    thumbnailContentId?: number;
    contentId?: number;
    link?: string;
}
export namespace Document {
    export type DocumentTypeEnum = 'Public' | 'Private';
    export const DocumentTypeEnum = {
        Public: 'Public' as DocumentTypeEnum,
        Private: 'Private' as DocumentTypeEnum
    };
}


