/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GeneralSettings { 
    id?: number;
    xmin?: number;
    groupName: string;
    label: string;
    value: string;
    dataType: GeneralSettings.DataTypeEnum;
}
export namespace GeneralSettings {
    export type DataTypeEnum = 'number' | 'string' | 'datetime' | 'boolean' | 'object';
    export const DataTypeEnum = {
        Number: 'number' as DataTypeEnum,
        String: 'string' as DataTypeEnum,
        Datetime: 'datetime' as DataTypeEnum,
        Boolean: 'boolean' as DataTypeEnum,
        Object: 'object' as DataTypeEnum
    };
}


