/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Person } from './person';


export interface PersonNotification { 
    id?: number;
    xmin?: number;
    person: Person;
    personNotificationType: PersonNotification.PersonNotificationTypeEnum;
    token: string;
}
export namespace PersonNotification {
    export type PersonNotificationTypeEnum = 'Web' | 'Android' | 'IoS';
    export const PersonNotificationTypeEnum = {
        Web: 'Web' as PersonNotificationTypeEnum,
        Android: 'Android' as PersonNotificationTypeEnum,
        IoS: 'IoS' as PersonNotificationTypeEnum
    };
}


