/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateSequence } from './coordinateSequence';
import { Geometry } from './geometry';
import { GeometryFactory } from './geometryFactory';
import { Coordinate } from './coordinate';
import { PrecisionModel } from './precisionModel';
import { Envelope } from './envelope';


export interface Point { 
    envelope?: Geometry;
    factory?: GeometryFactory;
    userData?: object;
    coordinates?: Array<Coordinate>;
    empty?: boolean;
    dimension?: number;
    simple?: boolean;
    y?: number;
    x?: number;
    boundaryDimension?: number;
    coordinateSequence?: CoordinateSequence;
    geometryType?: string;
    coordinate?: Coordinate;
    numPoints?: number;
    boundary?: Geometry;
    length?: number;
    valid?: boolean;
    envelopeInternal?: Envelope;
    srid?: number;
    numGeometries?: number;
    precisionModel?: PrecisionModel;
    interiorPoint?: Point;
    rectangle?: boolean;
    centroid?: Point;
    area?: number;
}

