/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Department } from './department';
import { BreakType } from './breakType';
import { Parameter } from './parameter';


export interface Profile { 
    id?: number;
    xmin?: number;
    breakType: BreakType;
    department?: Department;
    schedularParam?: Parameter;
    breakParam?: Parameter;
    name?: string;
    dayType?: Profile.DayTypeEnum;
}
export namespace Profile {
    export type DayTypeEnum = 'SPESIFIC' | 'CUSTOM';
    export const DayTypeEnum = {
        Spesific: 'SPESIFIC' as DayTypeEnum,
        Custom: 'CUSTOM' as DayTypeEnum
    };
}


