/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BreakType } from './breakType';
import { Profile } from './profile';


export interface ProfileBreak { 
    id?: number;
    xmin?: number;
    dayType?: ProfileBreak.DayTypeEnum;
    profile?: Profile;
    breakType?: BreakType;
    day?: string;
    startTime?: string;
    endedTime?: string;
    fullTimeStart?: string;
    fullTimeEnd?: string;
}
export namespace ProfileBreak {
    export type DayTypeEnum = 'SPESIFIC' | 'CUSTOM';
    export const DayTypeEnum = {
        Spesific: 'SPESIFIC' as DayTypeEnum,
        Custom: 'CUSTOM' as DayTypeEnum
    };
}


