/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Tickets } from './tickets';


export interface TicketProcess { 
    id?: number;
    xmin?: number;
    ticket?: Tickets;
    user?: User;
    processDate?: string;
    ticketProcessType?: TicketProcess.TicketProcessTypeEnum;
    emailList?: string;
    phoneNumberList?: string;
    result: string;
    callStationNumber?: number;
    callNumber?: string;
    callResult?: string;
    callFileName?: string;
}
export namespace TicketProcess {
    export type TicketProcessTypeEnum = 'New' | 'Phone' | 'Email' | 'Note' | 'Category' | 'Statuses' | 'Priority';
    export const TicketProcessTypeEnum = {
        New: 'New' as TicketProcessTypeEnum,
        Phone: 'Phone' as TicketProcessTypeEnum,
        Email: 'Email' as TicketProcessTypeEnum,
        Note: 'Note' as TicketProcessTypeEnum,
        Category: 'Category' as TicketProcessTypeEnum,
        Statuses: 'Statuses' as TicketProcessTypeEnum,
        Priority: 'Priority' as TicketProcessTypeEnum
    };
}


