/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenDepartment { 
    clientId?: string;
    username?: string;
    userId?: number;
    departmentId?: number;
    departmentName?: string;
    departmentSearchCode?: string;
    departmentTypeId?: number;
    personId?: number;
    departmentLocationId?: number;
    departmentLocationSearchCode?: string;
}

