/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Department } from './department';
import { User } from './user';


export interface UserDepartmentRole { 
    id?: number;
    xmin?: number;
    user: User;
    department: Department;
    role: Role;
}

