/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleGrantedAuthority } from './simpleGrantedAuthority';
import { TokenDepartment } from './tokenDepartment';


export interface UserView { 
    clientId?: string;
    userId?: number;
    userName?: string;
    ipAddress?: string;
    departmentSearchCode?: string;
    department?: TokenDepartment;
    departmentId?: number;
    access_token?: string;
    roleList?: Array<number>;
    authorities?: Array<SimpleGrantedAuthority>;
    personId?: number;
    departmentLocationId?: number;
    departmentLocationSearchCode?: string;
    departmentTypeId?: number;
    path?: string;
    registrationId?: string;
}

