/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Worker } from './worker';
import { Profile } from './profile';


export interface WorkerProfile { 
    id?: number;
    xmin?: number;
    worker: Worker;
    profile: Profile;
    isValid?: boolean;
}

