/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Device } from './device';
import { WorkerProfile } from './workerProfile';


export interface WorkerActivity { 
    id?: number;
    xmin?: number;
    workerProfile: WorkerProfile;
    device: Device;
    activityType?: WorkerActivity.ActivityTypeEnum;
    activityDate?: string;
}
export namespace WorkerActivity {
    export type ActivityTypeEnum = 'CHECKIN' | 'CHECKOUT' | 'BREAKIN' | 'BREAKOUT';
    export const ActivityTypeEnum = {
        Checkin: 'CHECKIN' as ActivityTypeEnum,
        Checkout: 'CHECKOUT' as ActivityTypeEnum,
        Breakin: 'BREAKIN' as ActivityTypeEnum,
        Breakout: 'BREAKOUT' as ActivityTypeEnum
    };
}


