export * from './announcementController.service';
import { AnnouncementControllerService } from './announcementController.service';
export * from './appController.service';
import { AppControllerService } from './appController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './authorityController.service';
import { AuthorityControllerService } from './authorityController.service';
export * from './binaryContentsController.service';
import { BinaryContentsControllerService } from './binaryContentsController.service';
export * from './breakTyperController.service';
import { BreakTyperControllerService } from './breakTyperController.service';
export * from './categoriesController.service';
import { CategoriesControllerService } from './categoriesController.service';
export * from './commonUnitsController.service';
import { CommonUnitsControllerService } from './commonUnitsController.service';
export * from './currencyUnitController.service';
import { CurrencyUnitControllerService } from './currencyUnitController.service';
export * from './customErrorController.service';
import { CustomErrorControllerService } from './customErrorController.service';
export * from './dashboardController.service';
import { DashboardControllerService } from './dashboardController.service';
export * from './departmentController.service';
import { DepartmentControllerService } from './departmentController.service';
export * from './departmentTypeController.service';
import { DepartmentTypeControllerService } from './departmentTypeController.service';
export * from './deviceController.service';
import { DeviceControllerService } from './deviceController.service';
export * from './deviceMobileController.service';
import { DeviceMobileControllerService } from './deviceMobileController.service';
export * from './documentController.service';
import { DocumentControllerService } from './documentController.service';
export * from './etlController.service';
import { EtlControllerService } from './etlController.service';
export * from './generalSettingsController.service';
import { GeneralSettingsControllerService } from './generalSettingsController.service';
export * from './groupsController.service';
import { GroupsControllerService } from './groupsController.service';
export * from './introspectionController.service';
import { IntrospectionControllerService } from './introspectionController.service';
export * from './languageMessagesController.service';
import { LanguageMessagesControllerService } from './languageMessagesController.service';
export * from './languagesController.service';
import { LanguagesControllerService } from './languagesController.service';
export * from './locationController.service';
import { LocationControllerService } from './locationController.service';
export * from './locationTypeController.service';
import { LocationTypeControllerService } from './locationTypeController.service';
export * from './mapController.service';
import { MapControllerService } from './mapController.service';
export * from './mediaController.service';
import { MediaControllerService } from './mediaController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './parameterController.service';
import { ParameterControllerService } from './parameterController.service';
export * from './pathDescriptionController.service';
import { PathDescriptionControllerService } from './pathDescriptionController.service';
export * from './personController.service';
import { PersonControllerService } from './personController.service';
export * from './personNotificationController.service';
import { PersonNotificationControllerService } from './personNotificationController.service';
export * from './prioritiesController.service';
import { PrioritiesControllerService } from './prioritiesController.service';
export * from './profileBreakController.service';
import { ProfileBreakControllerService } from './profileBreakController.service';
export * from './profileController.service';
import { ProfileControllerService } from './profileController.service';
export * from './profileScheduleController.service';
import { ProfileScheduleControllerService } from './profileScheduleController.service';
export * from './profilesController.service';
import { ProfilesControllerService } from './profilesController.service';
export * from './reportController.service';
import { ReportControllerService } from './reportController.service';
export * from './roleController.service';
import { RoleControllerService } from './roleController.service';
export * from './staController.service';
import { StaControllerService } from './staController.service';
export * from './stateStoringController.service';
import { StateStoringControllerService } from './stateStoringController.service';
export * from './statusesController.service';
import { StatusesControllerService } from './statusesController.service';
export * from './ticketProcessController.service';
import { TicketProcessControllerService } from './ticketProcessController.service';
export * from './ticketsController.service';
import { TicketsControllerService } from './ticketsController.service';
export * from './uploadPluginController.service';
import { UploadPluginControllerService } from './uploadPluginController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './workerActivityController.service';
import { WorkerActivityControllerService } from './workerActivityController.service';
export * from './workerController.service';
import { WorkerControllerService } from './workerController.service';
export * from './workerLeaveController.service';
import { WorkerLeaveControllerService } from './workerLeaveController.service';
export * from './workerProfileController.service';
import { WorkerProfileControllerService } from './workerProfileController.service';
export * from './workerPropertyController.service';
import { WorkerPropertyControllerService } from './workerPropertyController.service';
export const APIS = [AnnouncementControllerService, AppControllerService, AuthControllerService, AuthorityControllerService, BinaryContentsControllerService, BreakTyperControllerService, CategoriesControllerService, CommonUnitsControllerService, CurrencyUnitControllerService, CustomErrorControllerService, DashboardControllerService, DepartmentControllerService, DepartmentTypeControllerService, DeviceControllerService, DeviceMobileControllerService, DocumentControllerService, EtlControllerService, GeneralSettingsControllerService, GroupsControllerService, IntrospectionControllerService, LanguageMessagesControllerService, LanguagesControllerService, LocationControllerService, LocationTypeControllerService, MapControllerService, MediaControllerService, NotificationControllerService, ParameterControllerService, PathDescriptionControllerService, PersonControllerService, PersonNotificationControllerService, PrioritiesControllerService, ProfileBreakControllerService, ProfileControllerService, ProfileScheduleControllerService, ProfilesControllerService, ReportControllerService, RoleControllerService, StaControllerService, StateStoringControllerService, StatusesControllerService, TicketProcessControllerService, TicketsControllerService, UploadPluginControllerService, UserControllerService, WorkerActivityControllerService, WorkerControllerService, WorkerLeaveControllerService, WorkerProfileControllerService, WorkerPropertyControllerService];
