/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

// @ts-ignore
import { GeoJsonModelView } from '../model/geoJsonModelView';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';



@Injectable({
  providedIn: 'root'
})
export class MapControllerService {

    protected basePath = 'http://localhost:8990';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string|string[], @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (Array.isArray(basePath) && basePath.length > 0) {
                basePath = basePath[0];
            }

            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }


    // @ts-ignore
    private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }

    private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
        if (value == null) {
            return httpParams;
        }

        if (typeof value === "object") {
            if (Array.isArray(value)) {
                (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
            } else if (value instanceof Date) {
                if (key != null) {
                    httpParams = httpParams.append(key, (value as Date).toISOString().substr(0, 10));
                } else {
                   throw Error("key may not be null if value is Date");
                }
            } else {
                Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                    httpParams, value[k], key != null ? `${key}.${k}` : k));
            }
        } else if (key != null) {
            httpParams = httpParams.append(key, value);
        } else {
            throw Error("key may not be null if value is not object or array");
        }
        return httpParams;
    }

    /**
     * @param layers 
     * @param z 
     * @param x 
     * @param y 
     * @param format 
     * @param buffer 
     * @param tileSize 
     * @param styles 
     * @param time 
     * @param sld 
     * @param sldBody 
     * @param cqlFilter 
     * @param bboxToBoundsViewparam 
     * @param accept 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public doGetSlippyWmsMap(layers: string, z: number, x: number, y: number, format: string, buffer?: number, tileSize?: number, styles?: string, time?: string, sld?: string, sldBody?: string, cqlFilter?: string, bboxToBoundsViewparam?: boolean, accept?: 'image/jpeg, image/jpg, image/png, image/gif', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'image/jpeg' | 'image/jpg' | 'image/png' | 'image/gif', context?: HttpContext}): Observable<Array<string>>;
    public doGetSlippyWmsMap(layers: string, z: number, x: number, y: number, format: string, buffer?: number, tileSize?: number, styles?: string, time?: string, sld?: string, sldBody?: string, cqlFilter?: string, bboxToBoundsViewparam?: boolean, accept?: 'image/jpeg, image/jpg, image/png, image/gif', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'image/jpeg' | 'image/jpg' | 'image/png' | 'image/gif', context?: HttpContext}): Observable<HttpResponse<Array<string>>>;
    public doGetSlippyWmsMap(layers: string, z: number, x: number, y: number, format: string, buffer?: number, tileSize?: number, styles?: string, time?: string, sld?: string, sldBody?: string, cqlFilter?: string, bboxToBoundsViewparam?: boolean, accept?: 'image/jpeg, image/jpg, image/png, image/gif', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'image/jpeg' | 'image/jpg' | 'image/png' | 'image/gif', context?: HttpContext}): Observable<HttpEvent<Array<string>>>;
    public doGetSlippyWmsMap(layers: string, z: number, x: number, y: number, format: string, buffer?: number, tileSize?: number, styles?: string, time?: string, sld?: string, sldBody?: string, cqlFilter?: string, bboxToBoundsViewparam?: boolean, accept?: 'image/jpeg, image/jpg, image/png, image/gif', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'image/jpeg' | 'image/jpg' | 'image/png' | 'image/gif', context?: HttpContext}): Observable<any> {
        if (layers === null || layers === undefined) {
            throw new Error('Required parameter layers was null or undefined when calling doGetSlippyWmsMap.');
        }
        if (z === null || z === undefined) {
            throw new Error('Required parameter z was null or undefined when calling doGetSlippyWmsMap.');
        }
        if (x === null || x === undefined) {
            throw new Error('Required parameter x was null or undefined when calling doGetSlippyWmsMap.');
        }
        if (y === null || y === undefined) {
            throw new Error('Required parameter y was null or undefined when calling doGetSlippyWmsMap.');
        }
        if (format === null || format === undefined) {
            throw new Error('Required parameter format was null or undefined when calling doGetSlippyWmsMap.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        if (buffer !== undefined && buffer !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>buffer, 'buffer');
        }
        if (tileSize !== undefined && tileSize !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>tileSize, 'tileSize');
        }
        if (styles !== undefined && styles !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>styles, 'styles');
        }
        if (time !== undefined && time !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>time, 'time');
        }
        if (sld !== undefined && sld !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sld, 'sld');
        }
        if (sldBody !== undefined && sldBody !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>sldBody, 'sld_body');
        }
        if (cqlFilter !== undefined && cqlFilter !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>cqlFilter, 'cql_filter');
        }
        if (bboxToBoundsViewparam !== undefined && bboxToBoundsViewparam !== null) {
          localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
            <any>bboxToBoundsViewparam, 'bboxToBoundsViewparam');
        }

        let localVarHeaders = this.defaultHeaders;
        if (accept !== undefined && accept !== null) {
            localVarHeaders = localVarHeaders.set('Accept', String(accept));
        }

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                'image/jpeg',
                'image/jpg',
                'image/png',
                'image/gif'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/map/tms/${this.configuration.encodeParam({name: "layers", value: layers, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/${this.configuration.encodeParam({name: "z", value: z, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/${this.configuration.encodeParam({name: "x", value: x, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}/${this.configuration.encodeParam({name: "y", value: y, in: "path", style: "simple", explode: false, dataType: "number", dataFormat: "int32"})}.${this.configuration.encodeParam({name: "format", value: format, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        return this.httpClient.request<Array<string>>('get', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param geoJsonModelView 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGeoJson(geoJsonModelView: GeoJsonModelView, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<string>;
    public getGeoJson(geoJsonModelView: GeoJsonModelView, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<HttpResponse<string>>;
    public getGeoJson(geoJsonModelView: GeoJsonModelView, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<HttpEvent<string>>;
    public getGeoJson(geoJsonModelView: GeoJsonModelView, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<any> {
        if (geoJsonModelView === null || geoJsonModelView === undefined) {
            throw new Error('Required parameter geoJsonModelView was null or undefined when calling getGeoJson.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                '*/*'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/map/geoJson`;
        return this.httpClient.request<string>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: geoJsonModelView,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param geoJsonModelView 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public publicGeoJson(geoJsonModelView: GeoJsonModelView, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<string>;
    public publicGeoJson(geoJsonModelView: GeoJsonModelView, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<HttpResponse<string>>;
    public publicGeoJson(geoJsonModelView: GeoJsonModelView, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<HttpEvent<string>>;
    public publicGeoJson(geoJsonModelView: GeoJsonModelView, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext}): Observable<any> {
        if (geoJsonModelView === null || geoJsonModelView === undefined) {
            throw new Error('Required parameter geoJsonModelView was null or undefined when calling publicGeoJson.');
        }

        let localVarHeaders = this.defaultHeaders;

        let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
        if (localVarHttpHeaderAcceptSelected === undefined) {
            // to determine the Accept header
            const httpHeaderAccepts: string[] = [
                '*/*'
            ];
            localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        }
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        let localVarHttpContext: HttpContext | undefined = options && options.context;
        if (localVarHttpContext === undefined) {
            localVarHttpContext = new HttpContext();
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/map/publicGeoJson`;
        return this.httpClient.request<string>('post', `${this.configuration.basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: geoJsonModelView,
                responseType: <any>responseType_,
                withCredentials: this.configuration.withCredentials,
                headers: localVarHeaders,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
